# Generated by Django 5.2.7 on 2026-02-12 18:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('handicap', models.FloatField(default=0)),
                ('puntos', models.FloatField(blank=True, default=0, null=True)),
                ('cn_totales', models.IntegerField(blank=True, default=0, null=True)),
                ('categoria', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jugadores',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('tipo', models.CharField(blank=True, default='handicap', max_length=50, null=True)),
                ('estado', models.CharField(choices=[('configuracion', 'Configuración'), ('equilibrado', 'Equilibrado')], default='configuracion', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'torneos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ParejaTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, choices=[('NS', 'Norte-Sur'), ('EO', 'Este-Oeste')], max_length=2, null=True)),
                ('handicap_pareja', models.FloatField()),
                ('posicion_final', models.IntegerField(blank=True, null=True)),
                ('porcentaje', models.FloatField(blank=True, null=True)),
                ('puntos_ranking', models.FloatField(blank=True, default=0, null=True)),
                ('jugador1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parejas_como_j1', to='bridge.jugador')),
                ('jugador2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parejas_como_j2', to='bridge.jugador')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parejas', to='bridge.torneo')),
            ],
            options={
                'db_table': 'parejas_torneo',
            },
        ),
    ]
