# Generated by Django 5.2.7 on 2026-02-12 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo_ranks', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_archivo_travellers', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('session_info', models.CharField(blank=True, max_length=200, null=True)),
                ('mesas', models.IntegerField(blank=True, null=True)),
                ('boards_totales', models.IntegerField(blank=True, null=True)),
                ('movimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('torneo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_importado', to='bridge.torneo')),
            ],
            options={
                'db_table': 'resultados_importados',
            },
        ),
        migrations.CreateModel(
            name='RankingImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField()),
                ('numero_pareja', models.IntegerField()),
                ('nombre_jugador1', models.CharField(max_length=150)),
                ('nombre_jugador2', models.CharField(max_length=150)),
                ('boards_jugados', models.IntegerField(blank=True, null=True)),
                ('total_puntos', models.FloatField(blank=True, null=True)),
                ('maximo_puntos', models.IntegerField(blank=True, null=True)),
                ('porcentaje', models.FloatField(blank=True, null=True)),
                ('handicap', models.FloatField(blank=True, null=True)),
                ('porcentaje_con_handicap', models.FloatField(blank=True, null=True)),
                ('puntos_asignados', models.FloatField(blank=True, default=0, null=True)),
                ('jugador1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rankings_como_j1', to='bridge.jugador')),
                ('jugador2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rankings_como_j2', to='bridge.jugador')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='bridge.resultadoimportado')),
            ],
            options={
                'db_table': 'rankings_importados',
                'ordering': ['posicion'],
            },
        ),
        migrations.CreateModel(
            name='ManoJugada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_numero', models.IntegerField()),
                ('pareja_ns', models.IntegerField(blank=True, null=True)),
                ('pareja_ew', models.IntegerField(blank=True, null=True)),
                ('contrato', models.CharField(blank=True, max_length=20, null=True)),
                ('declarante', models.CharField(blank=True, max_length=5, null=True)),
                ('salida', models.CharField(blank=True, max_length=10, null=True)),
                ('puntos_ns_positivo', models.IntegerField(blank=True, null=True)),
                ('puntos_ns_negativo', models.IntegerField(blank=True, null=True)),
                ('mp_ns', models.FloatField(blank=True, null=True)),
                ('mp_ew', models.FloatField(blank=True, null=True)),
                ('nombre_pareja_ns', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre_pareja_ew', models.CharField(blank=True, max_length=200, null=True)),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manos', to='bridge.resultadoimportado')),
            ],
            options={
                'db_table': 'manos_jugadas',
                'ordering': ['board_numero', '-mp_ns'],
            },
        ),
    ]
