# Generated by Django 5.2.7 on 2026-02-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0002_resultadoimportado_rankingimportado_manojugada'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoimportado',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
