# Generated by Django 5.2.7 on 2026-02-13 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0003_resultadoimportado_confirmado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'db_table': 'lugares',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='jugador',
            name='es_director',
            field=models.BooleanField(default=False, verbose_name='Autorizado como Director'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='director',
            field=models.ForeignKey(blank=True, limit_choices_to={'es_director': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torneos_dirigidos', to='bridge.jugador', verbose_name='Director del Torneo'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torneos', to='bridge.lugar', verbose_name='Lugar/Sede'),
        ),
    ]
