# Generated by Django 5.2.1 on 2026-02-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bridge", "0004_lugar_jugador_es_director_torneo_director_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jugador",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="jugadores/fotos/",
                verbose_name="Foto de perfil",
            ),
        ),
    ]
